Karel/layout - created homepage and study options based on materials in figma
cesko-digital/zacni-ucit pull request #40
Opened 2021-03-01 15:52 UTC by KarelGeyer

Couple of components were created:

**Homepage** 
folder 
- can be found -> frontend -> pages -> Homepage (localhost:3000/homepage)
- needs to be redesigned to match with version 3.0 (will be done in next few days)
- added responsivity (only phone version) 
- all styled using Styled components, 
-  based on version 0.5, for now, its components are:
1.  DropDowns.tsx - basic styled inputs to choose your education, course and additional qualification, under inputs there is a search button.
2.  Headline.tsx - Headline and Subheadline

**StudyOptions*
- can be found -> frontend -> pages -> StudyOptions (localhost:3000/studyoptions)
- design based on version 3.0
- added responsivity (only phone version) 
- all styled using Styled components, Material UI for icons
- its components are: 
1. Heading.tsx - headings, title, qualification, some text, filter button
2. Selection.tsx - selection based on Tile, Qualification, CŽV
3. Results.tsx - containers for each university

**Footer**
- Footer can be found in - folder layout -> footer -> Footer.tsx
- once again only used Styled Components
- its responsive (only phone version)
- imported in Layout.tsx bellow MaxWidth component

also installed material UI Core and Icons

2021-03-02 17:08 UTC, jpetera54 commented
Za mě ok, klidně mergnout.
Super práce Karle

2021-03-03 10:16 UTC, steveheaven commented on frontend/layout/footer/Footer.tsx
> +const FooterH3 = styled.h3 `
všechny "há" elementy(h1, h2,...) bych v moderním vývoji moc nepoužíval, lepší je div nebo span nastylovanej podle globálních pravidel v layout/Theme.ts...há trojky mají tendenci se za určitých okolností chovat na více prohlížečích různě(třeba v Chromu to jede v pohodě, ale v Mozille máš font defaultní, apod...)

2021-03-06 17:03 UTC, steveheaven requested changes

2021-03-06 17:28 UTC, KarelGeyer commented on frontend/layout/footer/Footer.tsx
> +
Sám tam nic neplánuju, nebyl jsem si ale jsitej jestli tam nebude nutné nějakou komponentu přidat. Složku teda mažu.

2021-03-06 17:28 UTC, KarelGeyer commented on frontend/layout/footer/Footer.tsx
> +
předělám :)

2021-03-06 17:30 UTC, KarelGeyer commented on frontend/pages/homepage/DropDowns.tsx
> +
ok do dalšího meetingu upravím.

2021-03-08 17:09 UTC, KarelGeyer commented on frontend/layout/footer/Footer.tsx
> +
pozn. Done

2021-03-08 17:26 UTC, KarelGeyer commented on frontend/layout/footer/Footer.tsx
> +
pozn. done

2021-03-08 17:31 UTC, KarelGeyer commented on frontend/pages/studyoptions/components/Results.tsx
> +
pozn. done

2021-03-08 17:34 UTC, KarelGeyer commented on frontend/layout/footer/Footer.tsx
> +
pozn. done

2021-03-08 17:35 UTC, KarelGeyer commented on frontend/pages/homepage/index.tsx
> +
pozn. done

2021-04-12 10:09 UTC, merged